package com.github.mkram17.bazaarutils.utils.bazaar.market.order;

import com.github.mkram17.bazaarutils.utils.bazaar.market.TransactionType;

/**
 * Immutable record representing a player's tracked bazaar order.
 *
 * <p>Identity is a {@code long id} generated by {@code TrackedOrdersStorage.nextId()} —
 * not a UUID, not a Hypixel-side identifier. Stable for the lifetime of the order.
 */
public record TrackedPlayerOrder(
        long id,
        String productId,
        TransactionType.Side side,
        double price,
        int originalAmount,
        int filledAmount,
        int claimedAmount,
        int lastKnownIndex,
        OrderState state,
        long placedAt,
        long lastUpdatedAt
) {
    public static final int UNANCHORED = -1;

    /** Remaining unfilled amount — may be stale until ordersScreen is read. */
    public int remainingAmount() {
        return originalAmount - filledAmount;
    }

    /** Filled but not yet claimed. */
    public int unclaimedFilled() {
        return filledAmount - claimedAmount;
    }

    /** Returns a copy with a different id. */
    public TrackedPlayerOrder withId(long newId) {
        return new TrackedPlayerOrder(newId, productId, side, price,
                originalAmount, filledAmount, claimedAmount,
                lastKnownIndex, state, placedAt, lastUpdatedAt);
    }

    /**
     * Accumulates a fill. Becomes {@link OrderState.Filled} when total >= originalAmount,
     * otherwise {@link OrderState.Partial}.
     */
    public TrackedPlayerOrder withFill(int amount) {
        long now   = System.currentTimeMillis();
        int  total = filledAmount + amount;
        OrderState newState = total >= originalAmount
                ? new OrderState.Filled(total, now)
                : new OrderState.Partial(total);
        return new TrackedPlayerOrder(id, productId, side, price,
                originalAmount, total, claimedAmount,
                lastKnownIndex, newState, placedAt, now);
    }

    /**
     * Accumulates a claim. Becomes terminal {@link OrderState.Claimed} when
     * {@code claimedAmount + amount >= ceiling} where ceiling is filledAmount (if known)
     * or originalAmount. Partial claims preserve the current state.
     */
    public TrackedPlayerOrder withClaim(int amount) {
        long now       = System.currentTimeMillis();
        int  newClaimed = claimedAmount + amount;
        int  ceiling    = filledAmount > 0 ? filledAmount : originalAmount;
        OrderState newState = newClaimed >= ceiling
                ? new OrderState.Claimed(newClaimed, now)
                : state;
        return new TrackedPlayerOrder(id, productId, side, price,
                originalAmount, filledAmount, newClaimed,
                lastKnownIndex, newState, placedAt, now);
    }

    /** Returns a cancelled copy of this order. */
    public TrackedPlayerOrder cancelled() {
        long now = System.currentTimeMillis();
        return new TrackedPlayerOrder(id, productId, side, price,
                originalAmount, filledAmount, claimedAmount,
                lastKnownIndex, new OrderState.Cancelled(now), placedAt, now);
    }

    /**
     * Returns a copy with {@code lastKnownIndex} updated.
     * {@code lastUpdatedAt} is preserved — reanchoring is positional bookkeeping, not a data event.
     */
    public TrackedPlayerOrder reanchored(int newIndex) {
        return new TrackedPlayerOrder(id, productId, side, price,
                originalAmount, filledAmount, claimedAmount,
                newIndex, state, placedAt, lastUpdatedAt);
    }
}